version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./target/schoolbell-1.0-SNAPSHOT.war:/usr/local/tomee/webapps/schoolbell.war"
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
